name = "SymbolicRubi"
uuid = "49eb5440-63fc-4f85-bef3-4a81c72ae326"
authors = ["Felix <felixgerick@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Metatheory = "e9d8d322-4543-424a-9be4-0cc815abe26c"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
Metatheory = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
